package com.codeassist.buildengine;

import android.content.Context;
import com.codeassist.buildengine.api.*;import com.codeassist.buildengine.api.BuildCallbacks.*;import com.codeassist.buildengine.core.TaskGraph;import com.codeassist.buildengine.project.ProjectModel;import com.codeassist.buildengine.toolchain.Toolchain;
import java.io.*;import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;

/** Complete build facade. With the Context constructor, all bundled assets are unpacked automatically. */
public final class BuildManager {
  private final ExecutorService executor=Executors.newCachedThreadPool(); private final Context context;
  public BuildManager(){this.context=null;} public BuildManager(Context context){this.context=context.getApplicationContext();}
  public BuildResult build(BuildRequest req, Progress progress) throws Exception {
    Objects.requireNonNull(req);if(progress==null)progress=(s,p)->{};final Progress cb=progress;
    Path toolRoot=req.toolchainPath, androidJar=req.androidJarPath;
    if(toolRoot==null||androidJar==null){if(context==null)throw new IllegalArgumentException("Pass toolchainPath/androidJarPath or use new BuildManager(context)");toolRoot=Toolchain.install(context);if(androidJar==null)androidJar=new Toolchain(toolRoot).androidJar();}
    validate(req,toolRoot,androidJar);final Path sdkJar=androidJar;final Toolchain tc=new Toolchain(toolRoot);
    Path work=(req.cachePath!=null?req.cachePath:req.projectPath.resolve(".codeassist")).toAbsolutePath();Files.createDirectories(work);ProjectModel model=ProjectModel.load(req.projectPath);
    Path out=req.outputPath!=null?req.outputPath:req.projectPath.resolve("build").resolve(req.buildType.name().toLowerCase()+(req.buildType==BuildType.AAB?".aab":".apk"));Files.createDirectories(out.toAbsolutePath().getParent());
    StringBuilder log=new StringBuilder();Path compiled=work.resolve("resources.zip"),linked=work.resolve("linked.apk"),linkedProto=work.resolve("linked-proto.apk"),classes=work.resolve("classes"),dex=work.resolve("dex"),mapping=work.resolve("mapping.txt");
    TaskGraph g=new TaskGraph();
    g.add("resources",()->{try{cb.onProgress("Compiling resources",15);run(log,tc.aapt2().toString(),"compile","--dir",model.res().toString(),"-o",compiled.toString());run(log,tc.aapt2().toString(),"link","-o",linked.toString(),"--java",work.resolve("gen").toString(),"--manifest",model.manifest.toString(),"-I",sdkJar.toString(),"--auto-add-overlay","--version-code","1","--version-name","1.0","--min-sdk-version",String.valueOf(model.minSdk),"--target-sdk-version",String.valueOf(model.targetSdk),compiled.toString());if(req.buildType==BuildType.AAB)run(log,tc.aapt2().toString(),"link","--proto-format","-o",linkedProto.toString(),"--manifest",model.manifest.toString(),"-I",sdkJar.toString(),"--auto-add-overlay","--version-code","1","--version-name","1.0","--min-sdk-version",String.valueOf(model.minSdk),"--target-sdk-version",String.valueOf(model.targetSdk),compiled.toString());}catch(Exception e){throw fail(e);}});
    g.add("java",()->{try{cb.onProgress("Compiling Java/Kotlin",35);Files.createDirectories(classes);List<String>src=new ArrayList<>();model.javaSources().forEach(p->src.add(p.toString()));Path gen=work.resolve("gen");if(Files.exists(gen))try(java.util.stream.Stream<Path>s=Files.walk(gen)){s.filter(p->p.toString().endsWith(".java")).forEach(p->src.add(p.toString()));}Path ecj=tc.ecj();if(!src.isEmpty()){List<String>a=new ArrayList<>(Arrays.asList("java","-jar",ecj.toString(),"-1.8","-proc:none","-d",classes.toString(),"-classpath",sdkJar.toString()));a.addAll(src);run(log,a.toArray(new String[0]));}Path kot=tc.find("kotlinc.jar");if(!model.kotlinSources().isEmpty()){if(kot==null)throw new IllegalStateException("kotlinc.jar is required for Kotlin sources");List<String>a=new ArrayList<>(Arrays.asList("java","-cp",kot.toString(),"org.jetbrains.kotlin.cli.jvm.K2JVMCompiler","-classpath",sdkJar.toString(),"-d",classes.toString()));model.kotlinSources().forEach(p->a.add(p.toString()));run(log,a.toArray(new String[0]));}}catch(Exception e){throw fail(e);}},"resources");
    g.add("dex",()->{try{cb.onProgress("Converting bytecode to DEX",55);Files.createDirectories(dex);Path program=work.resolve("classes.jar");jarDirectory(classes,program);Path r=req.buildType==BuildType.RELEASE_APK&&req.shrink?tc.r8():null;Path tool=r!=null?r:tc.d8();List<String>a=new ArrayList<>(Arrays.asList("java","-cp",tool.toString(),r!=null?"com.android.tools.r8.R8":"com.android.tools.r8.D8","--lib",sdkJar.toString(),"--output",dex.toString()));if(r!=null){Path rules=work.resolve("proguard.pro");if(!Files.exists(rules))Files.write(rules,Arrays.asList("-dontwarn **"),java.nio.charset.StandardCharsets.UTF_8);a.add("--pg-conf");a.add(rules.toString());a.add("--pg-map-output");a.add(mapping.toString());}a.add(program.toString());run(log,a.toArray(new String[0]));}catch(Exception e){throw fail(e);}},"java");
    g.add("package",()->{try{cb.onProgress("Packaging output",75);Path unsigned=work.resolve("unsigned.apk");mergeZip(linked,dex,unsigned,false);if(req.buildType==BuildType.AAB){Path module=work.resolve("base.zip");mergeModuleZip(linkedProto,dex,module);run(log,"java","-jar",tc.bundletool().toString(),"build-bundle","--modules="+module,"--output="+out);signBundle(req,out,log);}else{Files.copy(unsigned,out,StandardCopyOption.REPLACE_EXISTING);if(req.buildType==BuildType.RELEASE_APK||req.signingConfig!=null)sign(req,tc,out,log);}cb.onProgress("Build complete",100);}catch(Exception e){throw fail(e);}},"dex");
    try{g.run();return new BuildResult(true,out,Files.exists(mapping)?mapping:null,log.toString());}catch(RuntimeException e){throw unwrap(e);}
  }
  public void buildAsync(BuildRequest r,Progress p,Completion c){executor.submit(()->{try{c.onComplete(build(r,p));}catch(Exception e){c.onComplete(new BuildResult(false,null,null,e.getMessage()));}});}public void close(){executor.shutdownNow();}
  private static void validate(BuildRequest r,Path tools,Path jar){if(!Files.isDirectory(tools))throw new IllegalArgumentException("Invalid toolchainPath");if(!Files.isDirectory(r.projectPath))throw new IllegalArgumentException("Invalid projectPath");if(!Files.isRegularFile(jar))throw new IllegalArgumentException("Invalid androidJarPath");if((r.buildType==BuildType.RELEASE_APK||r.buildType==BuildType.AAB)&&r.signingConfig==null)throw new IllegalArgumentException("Release/AAB requires signingConfig");}
  private static void sign(BuildRequest r,Toolchain t,Path apk,StringBuilder log)throws Exception{SigningConfig s=r.signingConfig;run(log,"java","-jar",t.apksigner().toString(),"sign","--ks",s.keystorePath.toString(),"--ks-key-alias",s.alias,"--ks-pass","pass:"+s.storePassword,"--key-pass","pass:"+s.keyPassword,"--v4-signing-enabled","true",apk.toString());}
  private static void signBundle(BuildRequest r,Path bundle,StringBuilder log)throws Exception{SigningConfig s=r.signingConfig;run(log,"jarsigner","-keystore",s.keystorePath.toString(),"-storepass",s.storePassword,"-keypass",s.keyPassword,bundle.toString(),s.alias);}
  private static void mergeZip(Path base,Path dir,Path out,boolean bundle)throws Exception{try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(out))){Set<String>seen=new HashSet<>();copyZip(base,z,seen);if(Files.exists(dir))try(java.util.stream.Stream<Path>s=Files.walk(dir)){s.filter(Files::isRegularFile).forEach(p->{try{ZipEntry e=new ZipEntry((bundle?"dex/":"")+p.getFileName());z.putNextEntry(e);Files.copy(p,z);z.closeEntry();}catch(IOException x){throw new UncheckedIOException(x);}});}}}
  private static void mergeModuleZip(Path base,Path dir,Path out)throws Exception{try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(out))){Set<String>seen=new HashSet<>();copyModuleZip(base,z,seen);if(Files.exists(dir))try(java.util.stream.Stream<Path>s=Files.walk(dir)){s.filter(Files::isRegularFile).forEach(p->{try{z.putNextEntry(new ZipEntry("dex/"+p.getFileName()));Files.copy(p,z);z.closeEntry();}catch(IOException x){throw new UncheckedIOException(x);}});}}}
  private static void copyModuleZip(Path p,ZipOutputStream z,Set<String>seen)throws Exception{try(ZipInputStream in=new ZipInputStream(Files.newInputStream(p))){ZipEntry e;byte[]b=new byte[8192];while((e=in.getNextEntry())!=null){if(e.isDirectory()||e.getName().equals("resources.arsc")||e.getName().startsWith("META-INF/"))continue;String n=e.getName().equals("AndroidManifest.xml")?"manifest/AndroidManifest.xml":e.getName();if(!seen.add(n))continue;z.putNextEntry(new ZipEntry(n));int k;while((k=in.read(b))>0)z.write(b,0,k);z.closeEntry();}}}
  private static void copyZip(Path p,ZipOutputStream z,Set<String>seen)throws Exception{try(ZipInputStream in=new ZipInputStream(Files.newInputStream(p))){ZipEntry e;byte[]b=new byte[8192];while((e=in.getNextEntry())!=null){if(!seen.add(e.getName())||e.isDirectory())continue;z.putNextEntry(new ZipEntry(e.getName()));int n;while((n=in.read(b))>0)z.write(b,0,n);z.closeEntry();}}}
  private static void jarDirectory(Path dir,Path jar)throws Exception{try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(jar))){if(!Files.exists(dir))return;try(java.util.stream.Stream<Path>s=Files.walk(dir)){s.filter(Files::isRegularFile).forEach(p->{try{z.putNextEntry(new ZipEntry(dir.relativize(p).toString().replace(File.separatorChar,'/')));Files.copy(p,z);z.closeEntry();}catch(IOException x){throw new UncheckedIOException(x);}});}}}
  private static void run(StringBuilder log,String...cmd)throws Exception{Process p=new ProcessBuilder(cmd).redirectErrorStream(true).start();try(BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()))){String s;while((s=r.readLine())!=null)log.append(s).append('\n');}if(p.waitFor()!=0)throw new IOException("Tool failed ("+cmd[0]+")\n"+log);}
  private static RuntimeException fail(Exception e){return new RuntimeException(e);}private static Exception unwrap(RuntimeException e){return e.getCause() instanceof Exception?(Exception)e.getCause():e;}
}
